api-hogs/bureaucrat

lib/bureaucrat/formatter.ex, lib/bureaucrat/helpers.ex, lib/bureaucrat/markdown_writer.ex, lib/bureaucrat/recorder.ex, mix.lock
Really love this tool!
I noticed that you can add a `desc` to `doc` but it wouldn't show up anywhere. I also wanted it to default to the test name. For that I turned `doc` into a macro.
That also allows us to generate the documentation in the same order as the tests are in the file. The one and only time we should order tests. :)
Lastly I added request and response headers and devided the payload up into two chunks.
This is all up for discussion, thanks for doing this!
Cheers
=> Add function name, order by line number and add request/response headers

lib/bureaucrat/markdown_writer.ex
`ex_doc` expects a linebreak after header to use the header text as the page title in documentation sidebar.
Add a single linebreak after header. :smiley_cat:
=> add linebreak to header for compat with ex_doc

lib/bureaucrat/swagger_slate_markdown_writer.ex
This PR contains a markdown writer module that merges data from a swagger spec, and outputs in a format that can be used with the [slate static site generator](https://github.com/tripit/slate).
Related Issues: #8, #9
I've only implemented enough to get our internal API docs generating successfully, but hopefully this is enough to get started.
[Example swagger file](https://gist.github.com/mbuhot/bdc13d96accea92d68514ea2193d1f42)
[Example generated output](https://gist.github.com/mbuhot/ae1c182c4de4897e910bd6b1e942e626)
Document structure is:
Overview
- From the swagger info section
Authentication
- From the swagger securityDefinitions section
Models
- From the swagger definitions section
- Nested models are flattened into a single table
Operations
- From the swagger paths section
- Groups …
=> Markdown writer including swagger info

README.md, lib/bureaucrat/helpers.ex, lib/bureaucrat/recorder.ex, lib/bureaucrat/swagger_slate_markdown_writer.ex, mix.exs, mix.lock
This PR adds an optional keyword list to be passed to the doc helper.
The motivation is to allow a custom swagger operationId to be passed through to the backend formatter.
The previous implementation assumed that the operationId was set based on the phoenix controller and action.
The implementation adds a new entry to the conn.assigns map: bureaucrat_opts which contains all the metadata from the test, including the description, line and any extra args provided at the call site.
This PR also updates the deps now that plug 1.0 is stable, and poison 3.0 has been released.
=> Keyword options for doc macro

lib/bureaucrat/formatter.ex, mix.exs
Elixir 1.4 prefers empty parenthesis when calling a local function.
=> Fix Elixir 1.4 warnings

README.md, lib/bureaucrat/formatter.ex, lib/bureaucrat/helpers.ex, lib/bureaucrat/markdown_writer.ex, lib/bureaucrat/recorder.ex, mix.exs
This implements generating documentation for Phoenix Channels messages, replies and broadcasts as suggested in #14. Connecting the socket and joining channels is not included yet.
Also, I've loosened the version constraint on poison (it's now in line with [phoenix](https://hex.pm/packages/phoenix/1.2.1)).
And I've fixed generating anchors and the table of contents in the `Bureaucrat.MarkdownWriter`.
There's still room for refactoring. But I'd need to test this against `Bureaucrat.SwaggerSlateMarkdownWriter`, which is currently not documented (and I haven't used it yet) -> #15.
=> Support phoenix channels (websockets) documentation

README.md, lib/bureaucrat/helpers.ex, lib/bureaucrat/markdown_writer.ex, mix.exs
When I recompiled my project from scratch with the added channels support, the compiler didn't recognize the Phoenix modules. While at it, I also fixed compiler warnings and made anchor links generation much more robust.
=> Add optional phoenix dependency, Fix compiler warnings, Fix channel anchor links

README.md, lib/bureaucrat/formatter.ex, lib/bureaucrat/helpers.ex, lib/bureaucrat/markdown_writer.ex, lib/bureaucrat/recorder.ex, lib/bureaucrat/util.ex, mix.exs
I've made two more changes:
1. New feature to include a markdown file as intro section for each output file, determined by output file path and name (e.g. `web/controllers/API_INTRO.md` for `web/controllers/API.md`). It's included before the table of contents (which then automatically gets the header `Endpoints`). We use this to document how to connect to the API and the different environments.
2. The formatter sorts the records by the line in the file it was recorded in. However, the sort order was lost due to the nature of Map keys (sorted for "small" maps) when using `Enum.group_by/2`. Thus, I've made a `stable_group_by/2` alternative that does the same but preserves sort order, and use it in the `MarkdownWriter`. This is particularly useful to document channels, as often tests …
=> Add custom intro section, Preserve test order

lib/bureaucrat/formatter.ex
GenEvent is deprecated.
> warning: passing GenEvent handlers (Bureaucrat.Formatter in this case) in the :formatters option of ExUnit is deprecated, please pass a GenServer instead. Check the documentation for the ExUnit.Formatter module for more information
=> Formatter should be a GenServer.

lib/bureaucrat/markdown_writer.ex
The sections `Request` and  `Response` should be separated by a new line to keep the proper markdown format.
=> Fix response section title

lib/bureaucrat/swagger_slate_markdown_writer.ex
Using swagger to generate API documentation, the parameters field is not generated as a map.  When swagger_slate_markdown_writer calls write_parameters, the method to update the parameters in the file never triggers because of the guard clause ` map_size(params) > 0`.
This pr updates that guard clause to accept lists as well as maps, and now the markdown_writer works as the documentation implies.
=> write parameters should handle lists as well as maps

lib/bureaucrat/api_blueprint_writer.ex
We had a couple of API documentation readers that weren't satisfied with the randomness of the examples in the API documentation.
This small pull request fixes the issue as it alphabetically sorts all the records before printing out the markdown.
=> Sort records in ApiBlueprintWriter

lib/bureaucrat/formatter.ex, lib/bureaucrat/markdown_writer.ex
There is an error when I try to document phoenix channels which comes from  `validate_records/1` function. This function assumes that all records have `private` attribute which is not true for `Phoenix.Socket.Message` struct and etc. 
This PR fixes this issue by refactoring `validate_records/1` to be able to handle all record types not just `Plug.Conn` struct
```
11:55:12.690 [error] GenServer #PID<0.395.0> terminating
** (ArgumentError) argument error
:erlang.apply(%Phoenix.Socket.Message{event: "subscribe", join_ref: nil, payload: %{result: []}, ref: nil, topic: "orders"}, :private, [])
(bureaucrat) lib/bureaucrat/formatter.ex:54: anonymous fn/1 in Bureaucrat.Formatter.validate_records/1
(elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
(bureaucrat) …
```
=> Fix an issue when documenting Phoenix Channels

lib/bureaucrat/markdown_writer.ex, lib/bureaucrat/recorder.ex
When we join a topic. We can reply message to client synchronously. (https://hexdocs.pm/phoenix/channels.html)
```
join :: {:ok, reply, socket}
```
Currently, Bureaucrat cannot generate document according to the reply above.
```elixir
describe "join" do
test "returns payload correctly", %{socket: socket} do
result = subscribe_and_join(socket, RoomChannel, "room:lobby")
assert  { :ok, %{ payload: "example" }, _ } = result
|> doc
end
end
```
* __Topic:__ room:lobby
* __Receive:__ ok
* __Body:__
... body payload
=> Support generate doc when join a topic

README.md, lib/bureaucrat/api_blueprint_writer.ex, lib/bureaucrat/json.ex, lib/bureaucrat/markdown_writer.ex, lib/bureaucrat/swagger_slate_markdown_writer.ex, mix.exs
Closes #43 
I'm not sure how to include a test of this, since there are no existing tests.
I have tried it in my own app, and it works as expected when `Jason` is the configured json library.
Only difference in the json output is that `Jason` seems to sort fields of an object alphabetically with `pretty: true`.
=> JSON library is now configurable. Defaults to Poison.

lib/bureaucrat/helpers.ex
`phoenix_swagger` sets a default operation_id when none is given, based
on the controller & action name
This change takes advantage of that by setting that same operation_id on
every `doc/1` call
Using the slate writer, this operation_id is mandatory on every `doc/1`
call, so this prevents us from having to set it on both sides just for
this purpose
=> Setting a default operation ID

lib/bureaucrat/helpers.ex
My previous PR had an issue that I failed to test
controllers wouldn't find the `find_operation_id` function, causing this to fail
I couldn't quite understand how to make it work, so in the meantime I inlined the code, and tested it more thoroughly this time
Happy to take suggestions on how to improve this though
=> Fixing default_operation_id

README.md, mix.exs
Previous behaviour: writer would ignore titles property.
New behaviour: apib writer uses the same code as the markdown writer to generate the group titles.
Note: My IDE updated the markdown to a more recent style. I don't think the rendered markdown looks any different. I can revert those changes if required. Let me know.
=> Update default directory to project root

lib/bureaucrat.ex, lib/bureaucrat/api_blueprint_writer.ex, lib/bureaucrat/recorder.ex
* Fixed the pattern matching errors in the api_blueprint_writer `write_parameters` and `write_response_body` functions.
* The pattern `params = %{}` matches any map, but the cases where it was used should have been matching an empty map. This resulted in the parameters not being registered.
* Updated the `anchor` function in api_blueprint_writer to print the correct key name, instead of always using "id", and to support multiple path params keys.
* updated how Bureaucrat.Recorder is called, removing the call to the deprecated Supervisor.Spec
=> Fixed pattern matching error in api_blueprint_writer

lib/bureaucrat/formatter.ex, mix.exs
between https://hexdocs.pm/ex_unit/1.11.4/ExUnit.Formatter.html
and https://hexdocs.pm/ex_unit/1.12.0/ExUnit.Formatter.html
it looks like the suite_finished events have changed.
to ensure backwards compatibility - both messages are captured.
=> Fixing for exunit >= 1.12

lib/bureaucrat/api_blueprint_writer.ex, lib/bureaucrat/markdown_writer.ex
Hi I added a new `bureaucrat_opts` called `detail`. 
This new opts is added, if present, after the `description` opts, only in the `Bureaucrat.MarkdownWriter` and `Bureaucrat.ApiBlueprintWriter` writers.
An example of use: 
```elixir
...
|> doc(
description: "Create a new Worklist",
detail: """
Markdown example
- item 1
- item 2
""")
```
=> Added `detail` to opts

lib/bureaucrat/helpers.ex
Got an error when using `doc()` for `assert_push()`:  
```
(KeyError) key :private not found in: %Phoenix.Socket.Message{event: "presence_state", join_ref: 29578, payload: %{uuids: ["9a17b8ea-9d6f-44e7-8ef7-ded250d723fd", "31a9ac03-640d-4368-b2c8-4271d14734a8"]}, ref: nil, topic: "presence:room"}
```
Here is a possible solution.
=> Fixed documenting channels

lib/bureaucrat/helpers.ex
Original [commit][1] missing the case when `Phoenix.Socket.Reply` send back to the socket and documented via `doc`.
Example code:
```
ref =
doc_push(socket, "update", %{
"score" => score
})
assert_reply(ref, :ok, data) |> doc
```
After an upgrade from `0.2.7` to the latest version as it was suggested in [issue][2] Reply was broken.
[1]: https://github.com/api-hogs/bureaucrat/commit/e9cce6e03b60c933a9aa3d34bb2a6b3a9c6f193d
[2]: https://github.com/api-hogs/bureaucrat/issues/71#issuecomment-913838455
=> Add ID fetcher from socket Reply operation

README.md, lib/bureaucrat/helpers.ex, lib/bureaucrat/markdown_writer.ex, lib/bureaucrat/recorder.ex
Hello 
I propose a new helper 'doc_connect'  in helper. 
Like the `doc_push` I copied the original `connect` macro of Phoenix.ChannelTest, to add a doc record with the params, and the result of `__connect__`. 
I'm not sure I choose the more relevant `default_operation_id`, not the best output format in the documentation. 
I'm open to better suggestions.
Regards
=> add helpers doc_connect to document a connect operation

README.md
In order to provide syntactically correct examples,
remove the parens on `conn` and add them to `doc` where
needed in the code samples given in the README.
Closes #https://github.com/api-hogs/bureaucrat/issues/76 (at least it cures the listed error).
=> Correct syntax in README examples

README.md, lib/bureaucrat/postman_writer.ex, test/postman_writer_test.exs
Simplify `PostmanWriter` readability by making json structure explicit.
Add `PostmanWriter` to README.
=> Postman writer improvements

README.md, lib/bureaucrat/macros.ex, test/macros_test.exs
Implement a way for `|> doc()` to be called automatically.
Added to readme and tested.
This is useful for huge applications that want to add `Bureaucrat` and can't afford to add `|> doc()` to every test.
=> Bureaucrat macros

lib/bureaucrat/helpers.ex, test/macros_test.exs
This PR adds two error messages that have cost our team a bit of time while we debugged. Hopefully they will save others some time!
Here are the two cases that we ran into, which we raised verbose errors for:
1. `phoenix_controller` and `phoenix_action`
- **DESCRIPTION**: When the Plug doesn't have a `phoenix_controller` and `phoenix_action`, it will fail. This happened for us when a Plug halted the `conn` early, in our case because of authentication. It failed with an opaque `MatchError`. 
- **FIX**: This PR raises a verbose error if the keys are missing in `Plug.Conn.private`.
- **TESTS**: The tests previously included cases where  `phoenix_controller` and `phoenix_action` were manually added to the `conn`. This PR adds tests without those, to prove that when they're missing, a correct …
=> Add error messages

lib/bureaucrat/swagger_slate_markdown_writer.ex
This pull request adds support for formatting HTML responses in the format_response function. Previously, the function assumed that the response body was always JSON and would try to format it accordingly. Now, the function checks the "content-type" header of the response to determine the correct format for the body.
If the "content-type" header indicates that the body is not HTML, the body is formatted as a JSON file instead. If the header is not present or if it does match the expected format for HTML, the body is still formatted as HTML.
This change improves the robustness of the code and makes it more flexible for different types of responses.
- Updated the format_response function to check the "content-type" header of the response to determine the correct format for the body.
- If …
=> Refactor response body formatting for HTML support

lib/bureaucrat/swagger_slate_markdown_writer.ex
Resolves #50 
This commit refactors the write_model_properties function to use Map.get/3 instead of the [] operator to access the "properties" key in model_schema. This change allows the function to handle nil values in model_schema without raising an exception.
The function now uses a case expression to pattern match on the result of Map.get/3 and returns the file argument if the value is nil. If the value is nil, the function proceeds with the rest of the logic as before.
The changes make the code more robust and consistent with the "Let it crash" philosophy in Erlang/Elixir, which suggests that the system should be built to handle failures by crashing and restarting processes to recover from errors.
=> Refactor write_model_properties function to handle nil values in model_schema

README.md, lib/bureaucrat/helpers.ex, test/macros_test.exs
resolves #96 
- if the caller of `doc` is not a test, `nil` is used as a default description
- if description is `nil` we search for the test caller at runtime, by looking at the stack trace of this process as well as its callers (to support invocations from tasks)
- if description is still `nil` a warning is printed and the request is not recorded
For simpler review I suggest reading one commit at a time.
=> Support doc from functions

lib/bureaucrat/macros.ex
doc() not run automatically on some tests due to them lacking content-type: "application/json" in reponse headers.
Check request headers for "application/json" instead
=> fix: get content header from req not res

lib/bureaucrat/postman_writer.ex, test/postman_writer_test.exs
Only accepted body as curly brace json
Accepts body with [] (through "_json"-key. As this by convention is how plug json parser accepts lists.
https://hexdocs.pm/plug/Plug.Parsers.JSON.html#content
=> feat: add support for req body as a list with "_json"

lib/bureaucrat/markdown_writer.ex
I have issue with Unicode characters:
```
16:37:13.502 pid=<0.1496.0> module=gen_server line=1373 [error] GenServer #PID<0.1496.0> terminating
** (stop) :no_translation
(stdlib 5.1.1) io.erl:103: :io.put_chars(#PID<0.1589.0>, [<<32, 32, 32, 32, 42, 32, 91, 99, 117, 114, 115, 111, 114, 58, 117, 112, 100, 97, 116, 101, 44, 32, 208, 189, 208, 181, 209, 129, 208, 186, 208, 190, 208, 187, 209, 140, 208, 186, 208, 190, 32, 208, 191, 208, 190, 208, 187, 209, 140, ...>>, 10])
(bureaucrat 0.2.10) lib/bureaucrat/markdown_writer.ex:220: Bureaucrat.MarkdownWriter.puts/2
(elixir 1.17.2) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
(bureaucrat 0.2.10) lib/bureaucrat/markdown_writer.ex:40: Bureaucrat.MarkdownWriter.write_table_of_contents/2
(bureaucrat 0.2.10) …
```
=> Fix  :no_translation relates of regular expression
